# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph/graph.ui'
#
# Created: Mon Jun 29 17:09:21 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(868, 1086)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.splitter_3 = QtGui.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.tabWidget = QtGui.QTabWidget(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.comboBox_selectPlot = QtGui.QComboBox(self.tab)
        self.comboBox_selectPlot.setObjectName(_fromUtf8("comboBox_selectPlot"))
        self.verticalLayout.addWidget(self.comboBox_selectPlot)
        self.checkBox_connect = QtGui.QCheckBox(self.tab)
        self.checkBox_connect.setChecked(True)
        self.checkBox_connect.setObjectName(_fromUtf8("checkBox_connect"))
        self.verticalLayout.addWidget(self.checkBox_connect)
        self.checkBox_points = QtGui.QCheckBox(self.tab)
        self.checkBox_points.setChecked(True)
        self.checkBox_points.setObjectName(_fromUtf8("checkBox_points"))
        self.verticalLayout.addWidget(self.checkBox_points)
        self.checkBox_grid = QtGui.QCheckBox(self.tab)
        self.checkBox_grid.setChecked(True)
        self.checkBox_grid.setObjectName(_fromUtf8("checkBox_grid"))
        self.verticalLayout.addWidget(self.checkBox_grid)
        self.checkBox_legend = QtGui.QCheckBox(self.tab)
        self.checkBox_legend.setObjectName(_fromUtf8("checkBox_legend"))
        self.verticalLayout.addWidget(self.checkBox_legend)
        self.btn_color1 = ColorButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_color1.sizePolicy().hasHeightForWidth())
        self.btn_color1.setSizePolicy(sizePolicy)
        self.btn_color1.setMaximumSize(QtCore.QSize(100, 23))
        self.btn_color1.setObjectName(_fromUtf8("btn_color1"))
        self.verticalLayout.addWidget(self.btn_color1)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_color2 = ColorButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_color2.sizePolicy().hasHeightForWidth())
        self.btn_color2.setSizePolicy(sizePolicy)
        self.btn_color2.setMaximumSize(QtCore.QSize(100, 23))
        self.btn_color2.setObjectName(_fromUtf8("btn_color2"))
        self.verticalLayout.addWidget(self.btn_color2)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.btn_color3 = ColorButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_color3.sizePolicy().hasHeightForWidth())
        self.btn_color3.setSizePolicy(sizePolicy)
        self.btn_color3.setMaximumSize(QtCore.QSize(100, 23))
        self.btn_color3.setObjectName(_fromUtf8("btn_color3"))
        self.verticalLayout.addWidget(self.btn_color3)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.btn_color4 = ColorButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_color4.sizePolicy().hasHeightForWidth())
        self.btn_color4.setSizePolicy(sizePolicy)
        self.btn_color4.setMaximumSize(QtCore.QSize(100, 23))
        self.btn_color4.setObjectName(_fromUtf8("btn_color4"))
        self.verticalLayout.addWidget(self.btn_color4)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.comboBox_symbol = QtGui.QComboBox(self.tab)
        self.comboBox_symbol.setObjectName(_fromUtf8("comboBox_symbol"))
        self.verticalLayout.addWidget(self.comboBox_symbol)
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12)
        self.slider_pointSize = QtGui.QSlider(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_pointSize.sizePolicy().hasHeightForWidth())
        self.slider_pointSize.setSizePolicy(sizePolicy)
        self.slider_pointSize.setMaximum(500)
        self.slider_pointSize.setSingleStep(1)
        self.slider_pointSize.setPageStep(50)
        self.slider_pointSize.setOrientation(QtCore.Qt.Horizontal)
        self.slider_pointSize.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_pointSize.setTickInterval(50)
        self.slider_pointSize.setObjectName(_fromUtf8("slider_pointSize"))
        self.verticalLayout.addWidget(self.slider_pointSize)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.slider_lineSize = QtGui.QSlider(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_lineSize.sizePolicy().hasHeightForWidth())
        self.slider_lineSize.setSizePolicy(sizePolicy)
        self.slider_lineSize.setMaximum(500)
        self.slider_lineSize.setSingleStep(1)
        self.slider_lineSize.setPageStep(50)
        self.slider_lineSize.setOrientation(QtCore.Qt.Horizontal)
        self.slider_lineSize.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_lineSize.setTickInterval(50)
        self.slider_lineSize.setObjectName(_fromUtf8("slider_lineSize"))
        self.verticalLayout.addWidget(self.slider_lineSize)
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.comboBox_selectImage = QtGui.QComboBox(self.tab)
        self.comboBox_selectImage.setObjectName(_fromUtf8("comboBox_selectImage"))
        self.verticalLayout.addWidget(self.comboBox_selectImage)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.btn_loadData = QtGui.QPushButton(self.tab_2)
        self.btn_loadData.setObjectName(_fromUtf8("btn_loadData"))
        self.verticalLayout_5.addWidget(self.btn_loadData)
        self.splitter_4 = QtGui.QSplitter(self.tab_2)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.tree_data = QtGui.QTreeWidget(self.splitter_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_data.sizePolicy().hasHeightForWidth())
        self.tree_data.setSizePolicy(sizePolicy)
        self.tree_data.setColumnCount(2)
        self.tree_data.setObjectName(_fromUtf8("tree_data"))
        self.tree_trace = QtGui.QTreeWidget(self.splitter_4)
        self.tree_trace.setColumnCount(2)
        self.tree_trace.setObjectName(_fromUtf8("tree_trace"))
        self.tree_image = QtGui.QTreeWidget(self.splitter_4)
        self.tree_image.setObjectName(_fromUtf8("tree_image"))
        self.verticalLayout_5.addWidget(self.splitter_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btn_newPlot = QtGui.QPushButton(self.tab_2)
        self.btn_newPlot.setObjectName(_fromUtf8("btn_newPlot"))
        self.horizontalLayout_5.addWidget(self.btn_newPlot)
        self.btn_newImage = QtGui.QPushButton(self.tab_2)
        self.btn_newImage.setObjectName(_fromUtf8("btn_newImage"))
        self.horizontalLayout_5.addWidget(self.btn_newImage)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tabWidget_2 = QtGui.QTabWidget(self.splitter_3)
        self.tabWidget_2.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.plot = PlotWidget(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot.sizePolicy().hasHeightForWidth())
        self.plot.setSizePolicy(sizePolicy)
        self.plot.setSizeIncrement(QtCore.QSize(10, 10))
        self.plot.setObjectName(_fromUtf8("plot"))
        self.horizontalLayout_6.addWidget(self.plot)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_5)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.image = ImageView(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setSizeIncrement(QtCore.QSize(10, 10))
        self.image.setObjectName(_fromUtf8("image"))
        self.horizontalLayout_4.addWidget(self.image)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.verticalLayout_7.addWidget(self.splitter_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.spin_x_min = SpinBox(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_x_min.sizePolicy().hasHeightForWidth())
        self.spin_x_min.setSizePolicy(sizePolicy)
        self.spin_x_min.setMinimumSize(QtCore.QSize(0, 0))
        self.spin_x_min.setMaximumSize(QtCore.QSize(75, 15))
        self.spin_x_min.setBaseSize(QtCore.QSize(30, 15))
        self.spin_x_min.setObjectName(_fromUtf8("spin_x_min"))
        self.spin_x_max = SpinBox(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_x_max.sizePolicy().hasHeightForWidth())
        self.spin_x_max.setSizePolicy(sizePolicy)
        self.spin_x_max.setMinimumSize(QtCore.QSize(0, 0))
        self.spin_x_max.setMaximumSize(QtCore.QSize(75, 15))
        self.spin_x_max.setBaseSize(QtCore.QSize(30, 15))
        self.spin_x_max.setObjectName(_fromUtf8("spin_x_max"))
        self.spin_y_max = SpinBox(self.splitter_2)
        self.spin_y_max.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_y_max.sizePolicy().hasHeightForWidth())
        self.spin_y_max.setSizePolicy(sizePolicy)
        self.spin_y_max.setMinimumSize(QtCore.QSize(0, 0))
        self.spin_y_max.setMaximumSize(QtCore.QSize(75, 15))
        self.spin_y_max.setBaseSize(QtCore.QSize(30, 15))
        self.spin_y_max.setObjectName(_fromUtf8("spin_y_max"))
        self.spin_y_min = SpinBox(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_y_min.sizePolicy().hasHeightForWidth())
        self.spin_y_min.setSizePolicy(sizePolicy)
        self.spin_y_min.setMinimumSize(QtCore.QSize(0, 0))
        self.spin_y_min.setMaximumSize(QtCore.QSize(75, 15))
        self.spin_y_min.setBaseSize(QtCore.QSize(30, 15))
        self.spin_y_min.setObjectName(_fromUtf8("spin_y_min"))
        self.verticalLayout_2.addWidget(self.splitter_2)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.label_3 = QtGui.QLabel(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(5, 10))
        self.label_3.setMaximumSize(QtCore.QSize(75, 100))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(5, 10))
        self.label_4.setMaximumSize(QtCore.QSize(75, 100))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label = QtGui.QLabel(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(5, 10))
        self.label.setMaximumSize(QtCore.QSize(75, 100))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(5, 10))
        self.label_2.setMaximumSize(QtCore.QSize(75, 100))
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.splitter)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.btn_setRange = QtGui.QPushButton(self.centralwidget)
        self.btn_setRange.setObjectName(_fromUtf8("btn_setRange"))
        self.horizontalLayout.addWidget(self.btn_setRange)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.btn_autoScaleX = QtGui.QPushButton(self.centralwidget)
        self.btn_autoScaleX.setObjectName(_fromUtf8("btn_autoScaleX"))
        self.verticalLayout_3.addWidget(self.btn_autoScaleX)
        self.btn_autoScaleY = QtGui.QPushButton(self.centralwidget)
        self.btn_autoScaleY.setObjectName(_fromUtf8("btn_autoScaleY"))
        self.verticalLayout_3.addWidget(self.btn_autoScaleY)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.checkBox_autoScale = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_autoScale.setChecked(True)
        self.checkBox_autoScale.setObjectName(_fromUtf8("checkBox_autoScale"))
        self.horizontalLayout_2.addWidget(self.checkBox_autoScale)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 868, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.actionFile = QtGui.QAction(MainWindow)
        self.actionFile.setObjectName(_fromUtf8("actionFile"))
        self.file_open = QtGui.QAction(MainWindow)
        self.file_open.setObjectName(_fromUtf8("file_open"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.file_update = QtGui.QAction(MainWindow)
        self.file_update.setObjectName(_fromUtf8("file_update"))
        self.actionCircle = QtGui.QAction(MainWindow)
        self.actionCircle.setCheckable(False)
        self.actionCircle.setEnabled(True)
        self.actionCircle.setObjectName(_fromUtf8("actionCircle"))
        self.actionSquare = QtGui.QAction(MainWindow)
        self.actionSquare.setObjectName(_fromUtf8("actionSquare"))
        self.actionTriangle = QtGui.QAction(MainWindow)
        self.actionTriangle.setObjectName(_fromUtf8("actionTriangle"))
        self.actionDiamond = QtGui.QAction(MainWindow)
        self.actionDiamond.setObjectName(_fromUtf8("actionDiamond"))
        self.actionPlus = QtGui.QAction(MainWindow)
        self.actionPlus.setObjectName(_fromUtf8("actionPlus"))
        self.menuFile.addAction(self.file_open)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_11.setText(_translate("MainWindow", "Plot to edit:", None))
        self.checkBox_connect.setText(_translate("MainWindow", "Connect", None))
        self.checkBox_points.setText(_translate("MainWindow", "Points", None))
        self.checkBox_grid.setText(_translate("MainWindow", "Grid", None))
        self.checkBox_legend.setText(_translate("MainWindow", "Legend", None))
        self.label_5.setText(_translate("MainWindow", "Background Color", None))
        self.label_6.setText(_translate("MainWindow", "Line Color", None))
        self.label_7.setText(_translate("MainWindow", "Point Color", None))
        self.label_8.setText(_translate("MainWindow", "Axis Color", None))
        self.label_12.setText(_translate("MainWindow", "Scatterplot Symbol", None))
        self.label_9.setText(_translate("MainWindow", "Point Size", None))
        self.label_10.setText(_translate("MainWindow", "Line Size", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Plot", None))
        self.btn_loadData.setText(_translate("MainWindow", "Load Data", None))
        self.tree_data.headerItem().setText(0, _translate("MainWindow", "DataStreams", None))
        self.tree_trace.headerItem().setText(0, _translate("MainWindow", "Traces", None))
        self.tree_image.headerItem().setText(0, _translate("MainWindow", "Image", None))
        self.tree_image.headerItem().setText(1, _translate("MainWindow", "2", None))
        self.btn_newPlot.setText(_translate("MainWindow", "Create New Plot", None))
        self.btn_newImage.setText(_translate("MainWindow", "Create New Image", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Calculate", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Tab 1", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Tab 2", None))
        self.label_3.setText(_translate("MainWindow", "x min", None))
        self.label_4.setText(_translate("MainWindow", "x max", None))
        self.label.setText(_translate("MainWindow", "y min", None))
        self.label_2.setText(_translate("MainWindow", "y max", None))
        self.btn_setRange.setText(_translate("MainWindow", "Set Range", None))
        self.btn_autoScaleX.setText(_translate("MainWindow", "Auto Scale X", None))
        self.btn_autoScaleY.setText(_translate("MainWindow", "Auto Scale Y", None))
        self.checkBox_autoScale.setText(_translate("MainWindow", "Auto Scale", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.actionFile.setText(_translate("MainWindow", "&File", None))
        self.actionFile.setShortcut(_translate("MainWindow", "F", None))
        self.file_open.setText(_translate("MainWindow", "&Open", None))
        self.file_open.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.file_update.setText(_translate("MainWindow", "Update", None))
        self.actionCircle.setText(_translate("MainWindow", "Circle", None))
        self.actionSquare.setText(_translate("MainWindow", "Square", None))
        self.actionTriangle.setText(_translate("MainWindow", "Triangle", None))
        self.actionDiamond.setText(_translate("MainWindow", "Diamond", None))
        self.actionPlus.setText(_translate("MainWindow", "Plus", None))

from imageview import ImageView
from pyqtgraph import SpinBox, ColorButton, PlotWidget
