# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph/tracetab.ui'
#
# Created: Tue Aug 04 13:16:29 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1163, 615)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout_14 = QtGui.QHBoxLayout(Form)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.splitter_2 = QtGui.QSplitter(Form)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter_2)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter_4 = QtGui.QSplitter(self.verticalLayoutWidget)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.tree_data = QtGui.QTreeWidget(self.splitter_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_data.sizePolicy().hasHeightForWidth())
        self.tree_data.setSizePolicy(sizePolicy)
        self.tree_data.setColumnCount(2)
        self.tree_data.setObjectName(_fromUtf8("tree_data"))
        self.verticalLayout.addWidget(self.splitter_4)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_17 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_17.setMaximumSize(QtCore.QSize(60, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_17.setFont(font)
        self.label_17.setTextFormat(QtCore.Qt.RichText)
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_12.addWidget(self.label_17)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.table_traces = QtGui.QTableWidget(self.verticalLayoutWidget)
        self.table_traces.setObjectName(_fromUtf8("table_traces"))
        self.table_traces.setColumnCount(5)
        self.table_traces.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_traces.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_traces.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_traces.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_traces.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_traces.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.table_traces)
        self.btn_newTrace = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btn_newTrace.setObjectName(_fromUtf8("btn_newTrace"))
        self.verticalLayout.addWidget(self.btn_newTrace)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_18 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_18.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_18.setFont(font)
        self.label_18.setTextFormat(QtCore.Qt.RichText)
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_13.addWidget(self.label_18)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_13.setMaximumSize(QtCore.QSize(25, 30))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_9.addWidget(self.label_13)
        self.combo_selectSource = QtGui.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_selectSource.sizePolicy().hasHeightForWidth())
        self.combo_selectSource.setSizePolicy(sizePolicy)
        self.combo_selectSource.setMaximumSize(QtCore.QSize(150, 20))
        self.combo_selectSource.setObjectName(_fromUtf8("combo_selectSource"))
        self.horizontalLayout_9.addWidget(self.combo_selectSource)
        self.label_14 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_14.setMaximumSize(QtCore.QSize(20, 30))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_9.addWidget(self.label_14)
        self.combo_select_val = QtGui.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_select_val.sizePolicy().hasHeightForWidth())
        self.combo_select_val.setSizePolicy(sizePolicy)
        self.combo_select_val.setMaximumSize(QtCore.QSize(150, 20))
        self.combo_select_val.setObjectName(_fromUtf8("combo_select_val"))
        self.horizontalLayout_9.addWidget(self.combo_select_val)
        self.label_15 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_15.setMaximumSize(QtCore.QSize(15, 30))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_9.addWidget(self.label_15)
        self.combo_select_arg = QtGui.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_select_arg.sizePolicy().hasHeightForWidth())
        self.combo_select_arg.setSizePolicy(sizePolicy)
        self.combo_select_arg.setMaximumSize(QtCore.QSize(150, 20))
        self.combo_select_arg.setObjectName(_fromUtf8("combo_select_arg"))
        self.horizontalLayout_9.addWidget(self.combo_select_arg)
        spacerItem2 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.table_slice = QtGui.QTableWidget(self.verticalLayoutWidget)
        self.table_slice.setObjectName(_fromUtf8("table_slice"))
        self.table_slice.setColumnCount(3)
        self.table_slice.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_slice.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_slice.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_slice.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.table_slice)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_16 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_16.setMaximumSize(QtCore.QSize(150, 25))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_16.setFont(font)
        self.label_16.setTextFormat(QtCore.Qt.RichText)
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_11.addWidget(self.label_16)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.checkBox_points = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_points.setMaximumSize(QtCore.QSize(16777215, 20))
        self.checkBox_points.setObjectName(_fromUtf8("checkBox_points"))
        self.horizontalLayout_10.addWidget(self.checkBox_points)
        self.checkBox_curve = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_curve.setMaximumSize(QtCore.QSize(16777215, 20))
        self.checkBox_curve.setObjectName(_fromUtf8("checkBox_curve"))
        self.horizontalLayout_10.addWidget(self.checkBox_curve)
        self.checkBox_fill = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_fill.setMaximumSize(QtCore.QSize(16777215, 20))
        self.checkBox_fill.setObjectName(_fromUtf8("checkBox_fill"))
        self.horizontalLayout_10.addWidget(self.checkBox_fill)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.table_appearance = QtGui.QTableWidget(self.verticalLayoutWidget)
        self.table_appearance.setShowGrid(True)
        self.table_appearance.setCornerButtonEnabled(True)
        self.table_appearance.setObjectName(_fromUtf8("table_appearance"))
        self.table_appearance.setColumnCount(2)
        self.table_appearance.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.table_appearance.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_appearance.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_appearance.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_appearance.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_appearance.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table_appearance.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table_appearance.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_appearance.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_appearance.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.table_appearance.setItem(2, 0, item)
        self.table_appearance.horizontalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.table_appearance)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.plot = PlotWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot.sizePolicy().hasHeightForWidth())
        self.plot.setSizePolicy(sizePolicy)
        self.plot.setSizeIncrement(QtCore.QSize(0, 0))
        self.plot.setObjectName(_fromUtf8("plot"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.spin_x_min = SpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_x_min.sizePolicy().hasHeightForWidth())
        self.spin_x_min.setSizePolicy(sizePolicy)
        self.spin_x_min.setMinimumSize(QtCore.QSize(0, 0))
        self.spin_x_min.setMaximumSize(QtCore.QSize(80, 15))
        self.spin_x_min.setBaseSize(QtCore.QSize(30, 15))
        self.spin_x_min.setObjectName(_fromUtf8("spin_x_min"))
        self.horizontalLayout.addWidget(self.spin_x_min)
        self.spin_x_max = SpinBox(self.layoutWidget)
        self.spin_x_max.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_x_max.sizePolicy().hasHeightForWidth())
        self.spin_x_max.setSizePolicy(sizePolicy)
        self.spin_x_max.setMinimumSize(QtCore.QSize(0, 0))
        self.spin_x_max.setMaximumSize(QtCore.QSize(80, 15))
        self.spin_x_max.setBaseSize(QtCore.QSize(30, 15))
        self.spin_x_max.setObjectName(_fromUtf8("spin_x_max"))
        self.horizontalLayout.addWidget(self.spin_x_max)
        self.spin_y_min = SpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_y_min.sizePolicy().hasHeightForWidth())
        self.spin_y_min.setSizePolicy(sizePolicy)
        self.spin_y_min.setMinimumSize(QtCore.QSize(0, 0))
        self.spin_y_min.setMaximumSize(QtCore.QSize(80, 15))
        self.spin_y_min.setBaseSize(QtCore.QSize(30, 15))
        self.spin_y_min.setObjectName(_fromUtf8("spin_y_min"))
        self.horizontalLayout.addWidget(self.spin_y_min)
        self.spin_y_max = SpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_y_max.sizePolicy().hasHeightForWidth())
        self.spin_y_max.setSizePolicy(sizePolicy)
        self.spin_y_max.setMinimumSize(QtCore.QSize(0, 0))
        self.spin_y_max.setMaximumSize(QtCore.QSize(80, 15))
        self.spin_y_max.setBaseSize(QtCore.QSize(30, 15))
        self.spin_y_max.setObjectName(_fromUtf8("spin_y_max"))
        self.horizontalLayout.addWidget(self.spin_y_max)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(5, 10))
        self.label_3.setMaximumSize(QtCore.QSize(40, 15))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(5, 10))
        self.label_4.setMaximumSize(QtCore.QSize(40, 15))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(5, 10))
        self.label.setMaximumSize(QtCore.QSize(40, 15))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(5, 10))
        self.label_2.setMaximumSize(QtCore.QSize(40, 15))
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.btn_autoScaleX = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_autoScaleX.sizePolicy().hasHeightForWidth())
        self.btn_autoScaleX.setSizePolicy(sizePolicy)
        self.btn_autoScaleX.setMaximumSize(QtCore.QSize(75, 25))
        self.btn_autoScaleX.setCheckable(True)
        self.btn_autoScaleX.setChecked(True)
        self.btn_autoScaleX.setObjectName(_fromUtf8("btn_autoScaleX"))
        self.verticalLayout_3.addWidget(self.btn_autoScaleX)
        self.btn_autoScaleY = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_autoScaleY.sizePolicy().hasHeightForWidth())
        self.btn_autoScaleY.setSizePolicy(sizePolicy)
        self.btn_autoScaleY.setMaximumSize(QtCore.QSize(75, 25))
        self.btn_autoScaleY.setCheckable(True)
        self.btn_autoScaleY.setChecked(True)
        self.btn_autoScaleY.setObjectName(_fromUtf8("btn_autoScaleY"))
        self.verticalLayout_3.addWidget(self.btn_autoScaleY)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.btnColor_background = ColorButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnColor_background.sizePolicy().hasHeightForWidth())
        self.btnColor_background.setSizePolicy(sizePolicy)
        self.btnColor_background.setMaximumSize(QtCore.QSize(75, 20))
        self.btnColor_background.setObjectName(_fromUtf8("btnColor_background"))
        self.verticalLayout_4.addWidget(self.btnColor_background)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(100, 15))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.btnColor_grid = ColorButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnColor_grid.sizePolicy().hasHeightForWidth())
        self.btnColor_grid.setSizePolicy(sizePolicy)
        self.btnColor_grid.setMaximumSize(QtCore.QSize(75, 20))
        self.btnColor_grid.setObjectName(_fromUtf8("btnColor_grid"))
        self.verticalLayout_2.addWidget(self.btnColor_grid)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(75, 15))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.checkBox_logX = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_logX.sizePolicy().hasHeightForWidth())
        self.checkBox_logX.setSizePolicy(sizePolicy)
        self.checkBox_logX.setMaximumSize(QtCore.QSize(16777215, 15))
        self.checkBox_logX.setObjectName(_fromUtf8("checkBox_logX"))
        self.verticalLayout_8.addWidget(self.checkBox_logX)
        self.checkBox_logY = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_logY.sizePolicy().hasHeightForWidth())
        self.checkBox_logY.setSizePolicy(sizePolicy)
        self.checkBox_logY.setMaximumSize(QtCore.QSize(16777215, 15))
        self.checkBox_logY.setObjectName(_fromUtf8("checkBox_logY"))
        self.verticalLayout_8.addWidget(self.checkBox_logY)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.checkBox_showGrid = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_showGrid.sizePolicy().hasHeightForWidth())
        self.checkBox_showGrid.setSizePolicy(sizePolicy)
        self.checkBox_showGrid.setMaximumSize(QtCore.QSize(16777215, 15))
        self.checkBox_showGrid.setObjectName(_fromUtf8("checkBox_showGrid"))
        self.verticalLayout_6.addWidget(self.checkBox_showGrid)
        self.checkBox_showLegend = QtGui.QCheckBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_showLegend.sizePolicy().hasHeightForWidth())
        self.checkBox_showLegend.setSizePolicy(sizePolicy)
        self.checkBox_showLegend.setMaximumSize(QtCore.QSize(16777215, 15))
        self.checkBox_showLegend.setObjectName(_fromUtf8("checkBox_showLegend"))
        self.verticalLayout_6.addWidget(self.checkBox_showLegend)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.checkBox_lockRatio = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_lockRatio.setMaximumSize(QtCore.QSize(16777215, 20))
        self.checkBox_lockRatio.setObjectName(_fromUtf8("checkBox_lockRatio"))
        self.horizontalLayout_2.addWidget(self.checkBox_lockRatio)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_14.addWidget(self.splitter_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.tree_data.headerItem().setText(0, _translate("Form", "DataStreams", None))
        self.label_17.setText(_translate("Form", "Traces", None))
        item = self.table_traces.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name", None))
        item = self.table_traces.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Show", None))
        item = self.table_traces.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Update", None))
        item = self.table_traces.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Appearance", None))
        self.btn_newTrace.setText(_translate("Form", "Create New Trace", None))
        self.label_18.setText(_translate("Form", "Trace Data", None))
        self.label_13.setText(_translate("Form", "From", None))
        self.label_14.setText(_translate("Form", "plot", None))
        self.label_15.setText(_translate("Form", "vs", None))
        item = self.table_slice.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Axis", None))
        item = self.table_slice.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Index", None))
        item = self.table_slice.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Value", None))
        self.label_16.setText(_translate("Form", "Trace Appearance ", None))
        self.checkBox_points.setText(_translate("Form", "Points", None))
        self.checkBox_curve.setText(_translate("Form", "Curve", None))
        self.checkBox_fill.setText(_translate("Form", "Fill", None))
        item = self.table_appearance.verticalHeaderItem(0)
        item.setText(_translate("Form", "Point Pen", None))
        item = self.table_appearance.verticalHeaderItem(1)
        item.setText(_translate("Form", "Point Outline", None))
        item = self.table_appearance.verticalHeaderItem(2)
        item.setText(_translate("Form", "Point Style", None))
        item = self.table_appearance.verticalHeaderItem(3)
        item.setText(_translate("Form", "Curve Pen", None))
        item = self.table_appearance.verticalHeaderItem(4)
        item.setText(_translate("Form", "Curve Shadow", None))
        item = self.table_appearance.verticalHeaderItem(5)
        item.setText(_translate("Form", "Fill", None))
        __sortingEnabled = self.table_appearance.isSortingEnabled()
        self.table_appearance.setSortingEnabled(False)
        self.table_appearance.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("Form", "x min", None))
        self.label_4.setText(_translate("Form", "x max", None))
        self.label.setText(_translate("Form", "y min", None))
        self.label_2.setText(_translate("Form", "y max", None))
        self.btn_autoScaleX.setText(_translate("Form", "Auto Scale X", None))
        self.btn_autoScaleY.setText(_translate("Form", "Auto Scale Y", None))
        self.label_6.setText(_translate("Form", "Background Color", None))
        self.label_5.setText(_translate("Form", "Grid Color", None))
        self.checkBox_logX.setText(_translate("Form", "Log X", None))
        self.checkBox_logY.setText(_translate("Form", "Log Y", None))
        self.checkBox_showGrid.setText(_translate("Form", "Show Grid", None))
        self.checkBox_showLegend.setText(_translate("Form", "Show Legend", None))
        self.checkBox_lockRatio.setText(_translate("Form", "Lock Ratio", None))

from pyqtgraph import SpinBox, PlotWidget
from colorButton import ColorButton
